# Retail Sales Analysis

Customer Behavior & Revenue Insights

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../data/raw/retail_sales_dataset.csv')
df.head()

,transaction_id,transaction_date,customer_id,customer_gender,customer_age_group,customer_segment,product_id,product_name,category,brand,quantity,unit_price,discount_pct,sales_amount,payment_method,sales_channel,region
0,T0000001,2024-04-24,C000820,Other,35-44,Returning,P1082,Dumbbells,Sports,Brand 1,2,313.53,20,501.65,Debit Card,Online,North
1,T0000002,2025-07-12,C002849,Other,45-54,New,P1087,Running Shoes,Sports,Brand 3,1,366.16,0,366.16,Credit Card,Online,South
2,T0000003,2025-06-01,C019727,Male,55+,Returning,P1030,Sneakers,Clothing,Brand 3,1,27.99,0,27.99,Gift Card,In-Store,South
3,T0000004,2025-08-26,C009116,Male,25-34,VIP,P1058,Sunscreen,Beauty,Brand 1,2,102.01,15,173.42,Cash,In-Store,South
4,T0000005,2024-12-10,C003350,Male,45-54,New,P1028,Sneakers,Clothing,Brand 1,1,259.55,0,259.55,Cash,In-Store,Central

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      120000 non-null  object
 1   transaction_date    120000 non-null  object
 2   customer_id         120000 non-null  object
 3   customer_gender     120000 non-null  object
 4   customer_age_group  120000 non-null  object
 5   customer_segment    120000 non-null  object
 6   product_id          120000 non-null  object
 7   product_name        120000 non-null  object
 8   category            120000 non-null  object
 9   brand               120000 non-null  object
 10  quantity            120000 non-null  int64
 11  unit_price          120000 non-null  float64
 12  discount_pct        120000 non-null  int64
 13  sales_amount        120000 non-null  float64
 14  payment_method      120000 non-null  object
 15  sales_channel       120000 non-null  object
 16  region              120000 non-null  object
dtypes: float64(2), int64(2), object(13)
memory usage: 15.6+ MB

# Dataset Inspection Using df.info()

The `df.info()` output shows that the dataset consists of **120,000** rows and **17 columns.**
 All columns contain `non‑null values`, indicating that there are no missing records.
Most columns are **categorical (object type)**, while key numerical fields such as 
- quantity, 
- unit_price, 
- discount_pct, and 
- sales_amount are already in numeric format.
The **transaction_date** column is currently stored as an object and will need to be converted to a `datetime` type for time‑based analysis.

# copy the dataframe to avoid modifying the original one

In [6]:
# copy the dataframe to avoid modifying the original one abd save in /data/cleaned/retail_sales_dataset_cleaned.csv
df_cleaned = df.copy()
# save the cleaned dataframe to a new csv file
df_cleaned.to_csv('../data/cleaned/retail_sales_dataset_cleaned.csv', index=False)  
df_cleaned.head()

,transaction_id,transaction_date,customer_id,customer_gender,customer_age_group,customer_segment,product_id,product_name,category,brand,quantity,unit_price,discount_pct,sales_amount,payment_method,sales_channel,region
0,T0000001,2024-04-24,C000820,Other,35-44,Returning,P1082,Dumbbells,Sports,Brand 1,2,313.53,20,501.65,Debit Card,Online,North
1,T0000002,2025-07-12,C002849,Other,45-54,New,P1087,Running Shoes,Sports,Brand 3,1,366.16,0,366.16,Credit Card,Online,South
2,T0000003,2025-06-01,C019727,Male,55+,Returning,P1030,Sneakers,Clothing,Brand 3,1,27.99,0,27.99,Gift Card,In-Store,South
3,T0000004,2025-08-26,C009116,Male,25-34,VIP,P1058,Sunscreen,Beauty,Brand 1,2,102.01,15,173.42,Cash,In-Store,South
4,T0000005,2024-12-10,C003350,Male,45-54,New,P1028,Sneakers,Clothing,Brand 1,1,259.55,0,259.55,Cash,In-Store,Central

In [7]:
# looking data types of the columns and column names
df_cleaned.info()
df_cleaned.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      120000 non-null  object
 1   transaction_date    120000 non-null  object
 2   customer_id         120000 non-null  object
 3   customer_gender     120000 non-null  object
 4   customer_age_group  120000 non-null  object
 5   customer_segment    120000 non-null  object
 6   product_id          120000 non-null  object
 7   product_name        120000 non-null  object
 8   category            120000 non-null  object
 9   brand               120000 non-null  object
 10  quantity            120000 non-null  int64
 11  unit_price          120000 non-null  float64
 12  discount_pct        120000 non-null  int64
 13  sales_amount        120000 non-null  float64
 14  payment_method      120000 non-null  object
 15  sales_channel       120000 non-null  object
 16  region              120000 non-null  object
dtypes: float64(2), int64(2), object(13)
memory usage: 15.6+ MB

Index(['transaction_id', 'transaction_date', 'customer_id', 'customer_gender',
       'customer_age_group', 'customer_segment', 'product_id', 'product_name',
       'category', 'brand', 'quantity', 'unit_price', 'discount_pct',
       'sales_amount', 'payment_method', 'sales_channel', 'region'],
      dtype='object')

## Inspecting Data Types and Column Names
Running `df_cleaned.info()` and `df_cleaned.columns` shows that the cleaned dataset contains **120,000 rows** and **17 columns**, with no  `missing` values across all fields. 
The output confirms that the column names are well structured and consistent, and the dataset is properly organized. However, the transaction_date column is an object, so it needs to be converted to a **datetime** format to support accurate **time‑based analysis**

In [11]:
# looking transaction_date column before conversion
df ['transaction_date'].head()

0    2024-04-24
1    2025-07-12
2    2025-06-01
3    2025-08-26
4    2024-12-10
Name: transaction_date, dtype: object

## Converting transaction_date to Datetime Format
The `transaction_date` column is currently stored as an `object` (string), which limits its use in `time‑based analysis`. To enable monthly and yearly trend analysis, the column is converted to a proper datetime format using pandas.

In [8]:
# Convert transaction_date to datetime
df_cleaned['transaction_date'] = pd.to_datetime(
    df_cleaned['transaction_date'], 
    errors='coerce'
)

In [18]:
# looking the transaction_date column after conversion data type.
# looking transaction_date column after conversion

df['transaction_date'].info()
print("\n")
df_cleaned['transaction_date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 120000 entries, 0 to 119999
Series name: transaction_date
Non-Null Count   Dtype
--------------   -----
120000 non-null  object
dtypes: object(1)
memory usage: 937.6+ KB


<class 'pandas.core.series.Series'>
RangeIndex: 120000 entries, 0 to 119999
Series name: transaction_date
Non-Null Count   Dtype
--------------   -----
120000 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 937.6 KB


### Comparing transaction_date Data Types Before and After Conversion

The **transaction_date column** was `object (text`) in the original dataset, meaning it was not recognized as a real date and could not support time analysis. After conversion in the cleaned dataset, it became `datetime64[ns]`, confirming successful conversion. Now it supports
 - sorting, 
 - filtering, and 
 - time-based analysis

In [25]:
# date conversion is successful, now we can create time-based columns for analysis
print(df_cleaned['transaction_date'].head())

0   2024-04-24
1   2025-07-12
2   2025-06-01
3   2025-08-26
4   2024-12-10
Name: transaction_date, dtype: datetime64[ns]

In [26]:
# Create time-based columns for analysis

# Create time-based features for analysis
df_cleaned['year'] = df_cleaned['transaction_date'].dt.year
df_cleaned['month'] = df_cleaned['transaction_date'].dt.month
df_cleaned['year_month'] = df_cleaned['transaction_date'].dt.to_period('M').astype(str)

In [29]:
# looking columns of the dataset after creating time-based columns
df_cleaned.head()

,transaction_id,transaction_date,customer_id,customer_gender,customer_age_group,customer_segment,product_id,product_name,category,brand,quantity,unit_price,discount_pct,sales_amount,payment_method,sales_channel,region,year,month,year_month
0,T0000001,2024-04-24,C000820,Other,35-44,Returning,P1082,Dumbbells,Sports,Brand 1,2,313.53,20,501.65,Debit Card,Online,North,2024,4,2024-04
1,T0000002,2025-07-12,C002849,Other,45-54,New,P1087,Running Shoes,Sports,Brand 3,1,366.16,0,366.16,Credit Card,Online,South,2025,7,2025-07
2,T0000003,2025-06-01,C019727,Male,55+,Returning,P1030,Sneakers,Clothing,Brand 3,1,27.99,0,27.99,Gift Card,In-Store,South,2025,6,2025-06
3,T0000004,2025-08-26,C009116,Male,25-34,VIP,P1058,Sunscreen,Beauty,Brand 1,2,102.01,15,173.42,Cash,In-Store,South,2025,8,2025-08
4,T0000005,2024-12-10,C003350,Male,45-54,New,P1028,Sneakers,Clothing,Brand 1,1,259.55,0,259.55,Cash,In-Store,Central,2024,12,2024-12

In [27]:
# looking time-based columns
df_cleaned[['transaction_date', 'year', 'month', 'year_month']].head()

  transaction_date  year  month year_month
0       2024-04-24  2024      4    2024-04
1       2025-07-12  2025      7    2025-07
2       2025-06-01  2025      6    2025-06
3       2025-08-26  2025      8    2025-08
4       2024-12-10  2024     12    2024-12

In [28]:
# Save final cleaned dataset
df_cleaned.to_csv("../data/cleaned/retail_sales_cleaned.csv", index=False)

print("Final cleaned dataset saved successfully.")

Final cleaned dataset saved successfully.